---
- name: install dependencies
  package:
    name: "{{ rm_packages }}"
    state: installed

- name: add redmine group
  group:
    name: "{{ rm_group }}"
    state: present

- name: add redmine user
  user:
    name: "{{ rm_user }}"
    state: present
    comment: redmine daemon user
    home: "{{ rm_home }}"
    group: "{{ rm_group }}"

- name: remove redmine .ssh directory
  file:
    state: absent
    path: "{{ rm_home }}/.ssh"

- name: create redmine directories
  file:
    name: "{{ item }}"
    state: directory
    mode: "0755"
    modification_time: preserve
    access_time: preserve
  with_items: "{{ rm_dirs }}"
  become: true
  become_user: "{{ rm_user }}"

- name: get redmine code
  git:
    repo: "{{ rm_git_url }}"
    dest: "{{ rm_app_dir }}"
    version: "{{ rm_version }}"
  become: true
  become_user: "{{ rm_user }}"
  register: git_updated

- name: create database config
  template:
    src: database.yml.j2
    dest: "{{ rm_app_dir }}/config/database.yml"
    mode: "0600"
  become: true
  become_user: "{{ rm_user }}"
  register: db_updated

- name: run bundler
  bundler:
    executable: "{{ rm_bundle }}"
    gem_path: "{{ rm_gem_dir }}"
    binstub_directory: "{{ rm_bin_dir }}"
    chdir: "{{ rm_app_dir }}"
    exclude_groups:
      - development
      - test
    state: present
  become: true
  become_user: "{{ rm_user }}"
  register: bundle_updated

- name: create session storage keys
  command: "env RAILS_ENV=production GEM_HOME={{ rm_gem_dir }}/ruby/{{ rm_ruby_version }} {{ rm_bundle }} exec rake generate_secret_token"
  args:
    chdir: "{{ rm_app_dir }}"
    creates: "{{ rm_app_dir }}/config/initializers/secret_token.rb"
  become: true
  become_user: "{{ rm_user }}"
  register: secret_updated

- name: migrate database
  command: "env RAILS_ENV=production REDMINE_LANG={{ rm_lang }} GEM_HOME={{ rm_gem_dir }}/ruby/{{ rm_ruby_version }} {{ rm_bundle }} exec rake db:migrate"
  args:
    chdir: "{{ rm_app_dir }}"
  become: true
  become_user: "{{ rm_user }}"
  when: git_updated.changed or db_updated.changed or bundle_updated.changed or secret_updated.changed or rm_rebuild

- name: load default data
  command: "env RAILS_ENV=production REDMINE_LANG={{ rm_lang }} GEM_HOME={{ rm_gem_dir }}/ruby/{{ rm_ruby_version }} {{ rm_bundle }} exec rake redmine:load_default_data"
  args:
    chdir: "{{ rm_app_dir }}"
  become: true
  become_user: "{{ rm_user }}"
  when: git_updated.changed or db_updated.changed or bundle_updated.changed or secret_updated.changed or rm_rebuild

- name: create rc script
  register: rc_status
  template:
    src: redmine.j2
    dest: /etc/rc.d/redmine
    owner: root
    group: wheel
    mode: 0755
