---
- name: install dependencies
  package:
    name: "{{ rm_packages }}"
    state: installed

- name: add redmine group
  group:
    name: "{{ rm_group }}"
    state: present

- name: add redmine user
  user:
    name: "{{ rm_user }}"
    state: present
    comment: redmine daemon user
    home: "{{ rm_home }}"
    group: "{{ rm_group }}"

- name: remove redmine .ssh directory
  file:
    state: absent
    path: "{{ rm_home }}/.ssh"

- name: create redmine directories
  file:
    name: "{{ item }}"
    state: directory
    mode: "0755"
    modification_time: preserve
    access_time: preserve
  with_items: "{{ rm_dirs }}"
  become: true
  become_user: "{{ rm_user }}"

- name: get redmine code
  git:
    repo: "{{ rm_git_url }}"
    dest: "{{ rm_app_dir }}"
    version: "{{ rm_version }}"
  become: true
  become_user: "{{ rm_user }}"
  notify:
    - migrate database
    - migrate plugins
    - load default data

- name: create database config
  template:
    src: database.yml.j2
    dest: "{{ rm_app_dir }}/config/database.yml"
    mode: "0600"
  become: true
  become_user: "{{ rm_user }}"
  notify:
    - migrate database
    - migrate plugins
    - load default data

- name: create local gemfile
  copy:
    src: Gemfile.local
    dest: "{{ rm_app_dir }}/Gemfile.local"
    mode: "0644"
  become: true
  become_user: "{{ rm_user }}"

- name: run bundler
  bundler:
    executable: "{{ rm_bundle }}"
    gem_path: "{{ rm_home }}"
    binstub_directory: "{{ rm_bin_dir }}"
    chdir: "{{ rm_app_dir }}"
    exclude_groups:
      - development
      - test
    state: present
  become: true
  become_user: "{{ rm_user }}"
  notify:
    - migrate database
    - migrate plugins
    - load default data

- name: create session storage keys
  command: "env RAILS_ENV=production GEM_HOME={{ rm_gem_dir }} {{ rm_bundle }} exec rake generate_secret_token"
  args:
    chdir: "{{ rm_app_dir }}"
    creates: "{{ rm_app_dir }}/config/initializers/secret_token.rb"
  become: true
  become_user: "{{ rm_user }}"
  notify:
    - migrate database
    - migrate plugins
    - load default data

- name: force rebuild databases
  command: /usr/bin/env true
  changed_when: rm_rebuild
  notify:
    - migrate database
    - migrate plugins
    - load default data

- name: create rc scripts
  template:
    src: "{{ item }}.j2"
    dest: "/etc/rc.d/{{ item }}"
    owner: root
    group: wheel
    mode: 0755
  with_items:
    - "redmine_unicorn"
    - "redmine_puma"
