---
- name: migrate database
  command: "env RAILS_ENV=production REDMINE_LANG={{ rm_lang }} GEM_HOME={{ rm_gem_dir }} {{ rm_bundle }} exec rake db:migrate"
  args:
    chdir: "{{ rm_app_dir }}"
  become: true
  become_user: "{{ rm_user }}"

- name: migrate plugins
  command: "env RAILS_ENV=production REDMINE_LANG={{ rm_lang }} GEM_HOME={{ rm_gem_dir }} {{ rm_bundle }} exec rake redmine:plugins:migrate"
  args:
    chdir: "{{ rm_app_dir }}"
  become: true
  become_user: "{{ rm_user }}"

- name: load default data
  command: "env RAILS_ENV=production REDMINE_LANG={{ rm_lang }} GEM_HOME={{ rm_gem_dir }} {{ rm_bundle }} exec rake redmine:load_default_data"
  args:
    chdir: "{{ rm_app_dir }}"
  become: true
  become_user: "{{ rm_user }}"
